from PyQt5 import QtCore, QtGui, QtWidgets


class MainWindowUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 700))
        MainWindow.setBaseSize(QtCore.QSize(700, 500))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1000, 700))
        self.centralwidget.setMaximumSize(QtCore.QSize(1000, 700))
        self.centralwidget.setBaseSize(QtCore.QSize(700, 500))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 13, 981, 681))
        self.layoutWidget.setObjectName("layoutWidget")
        self.MainLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.MainLayout.setContentsMargins(0, 0, 0, 0)
        self.MainLayout.setObjectName("MainLayout")
        self.InputLayout = QtWidgets.QVBoxLayout()
        self.InputLayout.setObjectName("InputLayout")
        self.parametersLabel = QtWidgets.QLabel(self.layoutWidget)
        self.parametersLabel.setMaximumSize(QtCore.QSize(300, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.parametersLabel.setFont(font)
        self.parametersLabel.setStyleSheet("")
        self.parametersLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.parametersLabel.setObjectName("parametersLabel")
        self.InputLayout.addWidget(self.parametersLabel)
        self.parameters = QtWidgets.QHBoxLayout()
        self.parameters.setObjectName("parameters")
        self.p = QtWidgets.QLineEdit(self.layoutWidget)
        self.p.setEnabled(True)
        self.p.setMinimumSize(QtCore.QSize(30, 20))
        self.p.setMaximumSize(QtCore.QSize(30, 20))
        self.p.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.p.setInputMask("")
        self.p.setMaxLength(1)
        self.p.setFrame(True)
        self.p.setObjectName("p")
        self.parameters.addWidget(self.p)
        self.spacer = QtWidgets.QLabel(self.layoutWidget)
        self.spacer.setMaximumSize(QtCore.QSize(10, 20))
        self.spacer.setObjectName("spacer")
        self.parameters.addWidget(self.spacer)
        self.n = QtWidgets.QLineEdit(self.layoutWidget)
        self.n.setMinimumSize(QtCore.QSize(60, 20))
        self.n.setMaximumSize(QtCore.QSize(30, 20))
        self.n.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.n.setMaxLength(5)
        self.n.setObjectName("n")
        self.parameters.addWidget(self.n)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.parameters.addItem(spacerItem)
        self.InputLayout.addLayout(self.parameters)
        self.primitivePolynomialLabel = QtWidgets.QLabel(self.layoutWidget)
        self.primitivePolynomialLabel.setMaximumSize(QtCore.QSize(250, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.primitivePolynomialLabel.setFont(font)
        self.primitivePolynomialLabel.setAcceptDrops(False)
        self.primitivePolynomialLabel.setStyleSheet("")
        self.primitivePolynomialLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.primitivePolynomialLabel.setObjectName("primitivePolynomialLabel")
        self.InputLayout.addWidget(self.primitivePolynomialLabel)
        self.InputScrollArea = QtWidgets.QScrollArea(self.layoutWidget)
        self.InputScrollArea.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.InputScrollArea.setWidgetResizable(True)
        self.InputScrollArea.setObjectName("InputScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 975, 160))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, 9, 971, 72))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lable = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lable.setObjectName("lable")
        self.verticalLayout.addWidget(self.lable)
        self.InputScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.InputLayout.addWidget(self.InputScrollArea)
        self.PrimitiveElementsGrid = QtWidgets.QGridLayout()
        self.PrimitiveElementsGrid.setObjectName("PrimitiveElementsGrid")
        self.InputLayout.addLayout(self.PrimitiveElementsGrid)
        self.PrimitieButtonsLayout = QtWidgets.QHBoxLayout()
        self.PrimitieButtonsLayout.setObjectName("PrimitieButtonsLayout")
        self.append = QtWidgets.QPushButton(self.layoutWidget)
        self.append.setStyleSheet("")
        self.append.setAutoDefault(False)
        self.append.setDefault(False)
        self.append.setFlat(False)
        self.append.setObjectName("append")
        self.PrimitieButtonsLayout.addWidget(self.append)
        self.delete_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.delete_2.setStyleSheet("")
        self.delete_2.setObjectName("delete_2")
        self.PrimitieButtonsLayout.addWidget(self.delete_2)
        self.clear = QtWidgets.QPushButton(self.layoutWidget)
        self.clear.setStyleSheet("")
        self.clear.setObjectName("clear")
        self.PrimitieButtonsLayout.addWidget(self.clear)
        self.InputLayout.addLayout(self.PrimitieButtonsLayout)
        self.submit = QtWidgets.QHBoxLayout()
        self.submit.setObjectName("submit")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.submit.addItem(spacerItem1)
        self.create_field = QtWidgets.QPushButton(self.layoutWidget)
        self.create_field.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_field.sizePolicy().hasHeightForWidth())
        self.create_field.setSizePolicy(sizePolicy)
        self.create_field.setMinimumSize(QtCore.QSize(300, 45))
        self.create_field.setMaximumSize(QtCore.QSize(300, 45))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.create_field.setFont(font)
        self.create_field.setMouseTracking(False)
        self.create_field.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.create_field.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.create_field.setStyleSheet("")
        self.create_field.setObjectName("create_field")
        self.submit.addWidget(self.create_field)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.submit.addItem(spacerItem2)
        self.InputLayout.addLayout(self.submit)
        self.MainLayout.addLayout(self.InputLayout)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.MainLayout.addWidget(self.line)
        self.EditLayout = QtWidgets.QHBoxLayout()
        self.EditLayout.setObjectName("EditLayout")
        self.CalcButtonsLayout = QtWidgets.QVBoxLayout()
        self.CalcButtonsLayout.setObjectName("CalcButtonsLayout")
        self.FieldElementsGrid = QtWidgets.QGridLayout()
        self.FieldElementsGrid.setObjectName("FieldElementsGrid")
        self.CalcButtonsLayout.addLayout(self.FieldElementsGrid)
        self.ButtonsLayout = QtWidgets.QGridLayout()
        self.ButtonsLayout.setObjectName("ButtonsLayout")
        self.add = QtWidgets.QPushButton(self.layoutWidget)
        self.add.setStyleSheet("\n"
"")
        self.add.setObjectName("add")
        self.ButtonsLayout.addWidget(self.add, 0, 0, 1, 1)
        self.multiply = QtWidgets.QPushButton(self.layoutWidget)
        self.multiply.setStyleSheet("")
        self.multiply.setObjectName("multiply")
        self.ButtonsLayout.addWidget(self.multiply, 0, 1, 1, 1)
        self.min = QtWidgets.QPushButton(self.layoutWidget)
        self.min.setStyleSheet("")
        self.min.setObjectName("min")
        self.ButtonsLayout.addWidget(self.min, 0, 2, 1, 1)
        self.clean = QtWidgets.QPushButton(self.layoutWidget)
        self.clean.setAutoFillBackground(False)
        self.clean.setStyleSheet("")
        self.clean.setObjectName("clean")
        self.ButtonsLayout.addWidget(self.clean, 0, 3, 1, 1)
        self.back = QtWidgets.QPushButton(self.layoutWidget)
        self.back.setStyleSheet("")
        self.back.setObjectName("back")
        self.ButtonsLayout.addWidget(self.back, 0, 4, 1, 1)
        self.CalcButtonsLayout.addLayout(self.ButtonsLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.CalcButtonsLayout.addItem(spacerItem3)
        self.EditLayout.addLayout(self.CalcButtonsLayout)
        self.OutputScrollArea = QtWidgets.QScrollArea(self.layoutWidget)
        self.OutputScrollArea.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.OutputScrollArea.setWidgetResizable(True)
        self.OutputScrollArea.setObjectName("OutputScrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 541, 328))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.OutputScrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.EditLayout.addWidget(self.OutputScrollArea)
        self.MainLayout.addLayout(self.EditLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Polynomial Calculator"))
        self.parametersLabel.setText(_translate("MainWindow", "Параметры поля:"))
        self.p.setText(_translate("MainWindow", "2"))
        self.spacer.setText(_translate("MainWindow", "^"))
        self.n.setText(_translate("MainWindow", "3"))
        self.primitivePolynomialLabel.setText(_translate("MainWindow", "Порождающий элемент поля:"))
        self.append.setText(_translate("MainWindow", "+"))
        self.delete_2.setText(_translate("MainWindow", "del"))
        self.clear.setText(_translate("MainWindow", "C"))
        self.create_field.setText(_translate("MainWindow", "Построить поле"))
        self.add.setText(_translate("MainWindow", "+"))
        self.multiply.setText(_translate("MainWindow", "*"))
        self.min.setText(_translate("MainWindow", "min"))
        self.clean.setText(_translate("MainWindow", "C"))
        self.back.setText(_translate("MainWindow", "back"))
