from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(700, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.InputLayout = QtWidgets.QHBoxLayout()
        self.InputLayout.setObjectName("InputLayout")
        self.FieldBox = QtWidgets.QGroupBox(self.centralwidget)
        self.FieldBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FieldBox.sizePolicy().hasHeightForWidth())
        self.FieldBox.setSizePolicy(sizePolicy)
        self.FieldBox.setMinimumSize(QtCore.QSize(160, 70))
        self.FieldBox.setMaximumSize(QtCore.QSize(160, 70))
        self.FieldBox.setFlat(False)
        self.FieldBox.setObjectName("FieldBox")
        self.label_2 = QtWidgets.QLabel(self.FieldBox)
        self.label_2.setGeometry(QtCore.QRect(140, 30, 16, 31))
        self.label_2.setPixmap(QtGui.QPixmap("f_2.svg"))
        self.label_2.setObjectName("label_2")
        self.p = QtWidgets.QLineEdit(self.FieldBox)
        self.p.setEnabled(True)
        self.p.setGeometry(QtCore.QRect(51, 40, 30, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p.sizePolicy().hasHeightForWidth())
        self.p.setSizePolicy(sizePolicy)
        self.p.setMinimumSize(QtCore.QSize(30, 20))
        self.p.setMaximumSize(QtCore.QSize(30, 20))
        self.p.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.p.setInputMask("")
        self.p.setMaxLength(1)
        self.p.setFrame(True)
        self.p.setObjectName("p")
        self.label_1 = QtWidgets.QLabel(self.FieldBox)
        self.label_1.setGeometry(QtCore.QRect(10, 30, 41, 30))
        self.label_1.setText("")
        self.label_1.setPixmap(QtGui.QPixmap("f_1.svg"))
        self.label_1.setObjectName("label_1")
        self.n = QtWidgets.QLineEdit(self.FieldBox)
        self.n.setGeometry(QtCore.QRect(85, 31, 50, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n.sizePolicy().hasHeightForWidth())
        self.n.setSizePolicy(sizePolicy)
        self.n.setMinimumSize(QtCore.QSize(50, 20))
        self.n.setMaximumSize(QtCore.QSize(50, 20))
        self.n.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.n.setMaxLength(5)
        self.n.setObjectName("n")
        self.InputLayout.addWidget(self.FieldBox)
        self.PolynomialBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PolynomialBox.sizePolicy().hasHeightForWidth())
        self.PolynomialBox.setSizePolicy(sizePolicy)
        self.PolynomialBox.setMaximumSize(QtCore.QSize(2000, 70))
        self.PolynomialBox.setObjectName("PolynomialBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.PolynomialBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.PolynomialBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.InputLayout.addWidget(self.PolynomialBox)
        self.verticalLayout.addLayout(self.InputLayout)
        self.PrPolynomialElemGrid = QtWidgets.QGridLayout()
        self.PrPolynomialElemGrid.setObjectName("PrPolynomialElemGrid")
        self.verticalLayout.addLayout(self.PrPolynomialElemGrid)
        self.PrButtonsLayout = QtWidgets.QHBoxLayout()
        self.PrButtonsLayout.setObjectName("PrButtonsLayout")
        self.append = QtWidgets.QPushButton(self.centralwidget)
        self.append.setStyleSheet("")
        self.append.setAutoDefault(False)
        self.append.setDefault(False)
        self.append.setFlat(False)
        self.append.setObjectName("append")
        self.PrButtonsLayout.addWidget(self.append)
        self.undo = QtWidgets.QPushButton(self.centralwidget)
        self.undo.setStyleSheet("")
        self.undo.setObjectName("undo")
        self.PrButtonsLayout.addWidget(self.undo)
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setStyleSheet("")
        self.clear.setObjectName("clear")
        self.PrButtonsLayout.addWidget(self.clear)
        self.verticalLayout.addLayout(self.PrButtonsLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FieldBox.setTitle(_translate("MainWindow", "Поле"))
        self.p.setText(_translate("MainWindow", "2"))
        self.n.setText(_translate("MainWindow", "3"))
        self.PolynomialBox.setTitle(_translate("MainWindow", "Порождающий полином:"))
        self.append.setText(_translate("MainWindow", "+"))
        self.undo.setText(_translate("MainWindow", "UNDO"))
        self.clear.setText(_translate("MainWindow", "C"))
